server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  # 连接远程仓库,具体有哪些属性可以配置可以在springcloud的官网上看。通过config-server可以连接到git，访问其中的资源和配置。
  cloud:
    config:
      server:
        git:
          # uri选码云上https的克隆链接
          uri: https://gitee.com/yunkai-zhang/spring-cloud-config.git
          # gitee不需要此项
          #skip-ssl-validation: true
          # gitee仓库不需要填用户名和密码
          #username: 用户名（一般是链接中自己名字的拼音）
          #password: 密码
        # github一定要加这个，不然会报错“fatal: unable to access Failed to connect to github.com port 443 after 21040 ms: Timed out”。github上是main，gitee上是master。但是gitee仓库不需要这个配置。
        #default-label: master
# 不加这个配置会报Cannot execute request on any known server 这个错：连接Eureka服务端地址不对
# 或者直接注释掉eureka依赖 这里暂时用不到eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false